# Etapa 1: Build da aplicação usando Maven
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app
COPY APIelectrum/pom.xml .
COPY APIelectrum/src ./src
RUN mvn clean package -DskipTests

# Etapa 2: Imagem final, apenas com o JAR
FROM eclipse-temurin:17-jdk
WORKDIR /app

# Copia o JAR gerado no build para a imagem final
COPY --from=builder /app/target/*.jar app.jar

# Expõe a porta definida no application.properties
EXPOSE 8081

# Define o comando de inicialização
ENTRYPOINT ["java", "-jar", "app.jar"]
